const EVENTS_HUMAN = [
  { time: 0.1, title: "人間の瞬き", description: "1回の瞬きは約0.1〜0.4秒。1分間に15-20回。", category: "人体" },
  { time: 0.15, title: "瞬きの平均", description: "瞬き1回約0.15秒。会話中は瞬きが減る。", category: "人体" },
  { time: 0.2, title: "プロの反応速度", description: "F1ドライバーやプロゲーマーの反応時間は約0.2秒。", category: "人体" },
  { time: 0.25, title: "心拍75回/分の1拍", description: "75回/分なら1拍0.8秒。60回/分なら1秒。", category: "人体" },
  { time: 0.5, title: "深呼吸1回", description: "深い呼吸1サイクル（吸う→吐く）は約4-6秒。半秒は吸気の始まり。", category: "人体" },
  { time: 0.8, title: "心拍75回/分", description: "安静時75bpmなら1拍0.8秒。", category: "人体" },
  { time: 1.0, title: "心拍60回/分の1拍", description: "安静時60bpmなら1拍ちょうど1秒。", category: "人体" },
  { time: 1.5, title: "視覚的反応（平均）", description: "視覚刺激への平均反応時間は約1.5秒。", category: "人体" },
  { time: 1.8, title: "平均的な反応時間", description: "視覚刺激に対する平均反応時間は約1.5〜2.0秒。", category: "人体" },
  { time: 2.0, title: "嗅覚の反応", description: "嗅覚は視覚より遅く、認識まで約2秒。", category: "人体" },
  { time: 2.1, title: "脳内信号の伝播", description: "2.1秒間に数十億のニューロンがスパイクで通信。", category: "人体" },
  { time: 3.0, title: "味覚の認識", description: "舌の味蕾が味を認識するまで約1-3秒。", category: "人体" },
  { time: 4.0, title: "深呼吸1サイクル", description: "深い呼吸1回（吸う→吐く）は約4-6秒。", category: "人体" },
  { time: 5.0, title: "触覚の反応", description: "皮膚の触覚受容器から脳への信号は約0.05秒。認識まで数秒。", category: "人体" },
  { time: 7.0, title: "ニコチンが脳に", description: "タバコのニコチンは約7秒で脳に到達。", category: "人体" },
  { time: 10.0, title: "あくびの伝播", description: "あくびは見た人に10秒以内に伝播することがある。", category: "人体" },
  { time: 13.0, title: "脳の画像処理（ms→秒）", description: "13ミリ秒＝0.013秒で画像認識。13秒は長すぎる。", category: "人体" },
  { time: 15.0, title: "1分間の瞬き回数", description: "1分間に15-20回瞬き。1回あたり約3-4秒間隔。", category: "人体" },
  { time: 20.0, title: "注意力の持続（短）", description: "集中力の波は約20秒周期と言われる。", category: "人体" },
  { time: 30.0, title: "短期記憶の保持", description: "短期記憶は約30秒保持。復唱しなければ忘れる。", category: "人体" },
  { time: 45.0, title: "歯磨き推奨時間（1/4）", description: "歯科医推奨の歯磨き時間は2-3分。45秒は短すぎ。", category: "人体" },
  { time: 60.0, title: "1分間の心拍", description: "安静時60bpmなら1分で60拍。", category: "人体" },
  { time: 90.0, title: "血液が体1周", description: "血液が心臓から全身1周するのに約60-90秒。", category: "人体" },
  { time: 120.0, title: "歯磨き推奨時間", description: "歯科医学会推奨：2-3分。2分＝120秒。", category: "人体" },
  { time: 180.0, title: "3分間の歯磨き", description: "推奨される歯磨き時間の上限。", category: "人体" },
  { time: 300.0, title: "集中力の限界", description: "「5分だけ」集中の限界。ポモドーロの短い休憩。", category: "人体" },
  { time: 600.0, title: "10分間の仮眠", description: "NASA研究：10-26分の仮眠が効果的。", category: "人体" },
  { time: 900.0, title: "15分の仮眠", description: "15分仮眠で認知機能が回復。長すぎると睡眠慣性。", category: "人体" },
  { time: 1500.0, title: "25分ポモドーロ", description: "ポモドーロ・テクニックの作業時間25分＝1500秒。", category: "人体" },
  { time: 3600.0, title: "アルコール代謝（1杯）", description: "ビール1杯の代謝に約1時間。3600秒。", category: "人体" },
  { time: 0.05, title: "触覚の神経速度", description: "触覚信号は約0.05秒で脊髄に到達。", category: "人体" },
  { time: 0.013, title: "脳の画像認識", description: "13ミリ秒で画像を認識。瞬きより速い。", category: "人体" },
  { time: 8.0, title: "息止め世界記録（短）", description: "プロのフリーダイバーは数分。8秒は入門。", category: "人体" },
  { time: 11.0, title: "世界息止め記録（旧）", description: "Aleix Seguraが24分03秒。11秒は一瞬。", category: "人体" },
  { time: 1443.0, title: "世界息止め記録", description: "2021年、Budimir Šobatが24分37秒（1477秒）。", category: "人体" },
];
