const EVENTS_MUSIC = [
  { time: 142, title: "Happy Birthday to You", description: "誕生日歌の典型的な長さ約2分22秒。142秒。", category: "音楽" },
  { time: 227, title: "Hey Jude", description: "ビートルズ「Hey Jude」約3分47秒（227秒）。", category: "音楽" },
  { time: 261, title: "Smells Like Teen Spirit", description: "Nirvana約4分21秒（261秒）。90年代を代表。", category: "音楽" },
  { time: 297, title: "Billie Jean", description: "マイケル・ジャクソン約4分57秒。Moonwalkの曲。", category: "音楽" },
  { time: 355, title: "Bohemian Rhapsody", description: "クイーン約5分55秒（355秒）。オペラ・ロック・バラードの融合。", category: "音楽" },
  { time: 360, title: "Stairway to Heaven", description: "レッド・ツェッペリン約8分2秒。360秒は途中。", category: "音楽" },
  { time: 482, title: "Stairway to Heaven（完）", description: "約8分2秒（482秒）。ロックの金字塔。", category: "音楽" },
  { time: 180, title: "3分のポップソング", description: "ポップソングの標準尺は3-4分。180秒＝3分。", category: "音楽" },
  { time: 240, title: "4分のジャズスタンダード", description: "ジャズのスタンダードは often 4分前後。", category: "音楽" },
  { time: 120, title: "2分のパンク曲", description: "パンクロックは often 2分以下。短く鋭く。", category: "音楽" },
  { time: 90, title: "1分30秒のCMソング", description: "CM用に編集された曲の短縮版。", category: "音楽" },
  { time: 60, title: "1分のインスト", description: "アニメやゲームの短いBGM。", category: "音楽" },
  { time: 30, title: "30秒のジングル", description: "テレビやラジオのジングル。30秒が定番。", category: "音楽" },
  { time: 15, title: "15秒のCM", description: "短尺CM用の15秒バージョン。", category: "音楽" },
  { time: 208, title: "Imagine", description: "ジョン・レノン約3分28秒（208秒）。", category: "音楽" },
  { time: 235, title: "Hotel California", description: "イーグルス約6分30秒。235秒は途中。", category: "音楽" },
  { time: 390, title: "Hotel California（完）", description: "約6分30秒（390秒）。ギターソロの名曲。", category: "音楽" },
  { time: 172, title: "Yesterday", description: "ビートルズ約2分52秒（172秒）。", category: "音楽" },
  { time: 199, title: "Purple Rain", description: "プリンス約8分41秒。199秒は序盤。", category: "音楽" },
  { time: 521, title: "Purple Rain（完）", description: "約8分41秒（521秒）。", category: "音楽" },
  { time: 245, title: "Sweet Child O' Mine", description: "Guns N' Roses約5分56秒。245秒は途中。", category: "音楽" },
  { time: 356, title: "Sweet Child O' Mine（完）", description: "約5分56秒（356秒）。", category: "音楽" },
  { time: 187, title: "Losing My Religion", description: "R.E.M.約4分47秒。187秒は途中。", category: "音楽" },
  { time: 287, title: "Losing My Religion（完）", description: "約4分47秒（287秒）。", category: "音楽" },
  { time: 0.5, title: "ドラムの1拍（120BPM）", description: "120BPMなら1拍0.5秒。4拍で2秒。", category: "音楽" },
  { time: 1.0, title: "60BPMの1拍", description: "60BPM＝1拍1秒。行進曲のテンポ。", category: "音楽" },
  { time: 0.25, title: "240BPMの1拍", description: "240BPM＝1拍0.25秒。速いメタル。", category: "音楽" },
  { time: 2.0, title: "120BPMの4拍", description: "120BPMで4拍＝2秒。1小節（4/4）。", category: "音楽" },
  { time: 4.0, title: "60BPMの4拍", description: "60BPMで4拍＝4秒。ゆったり1小節。", category: "音楽" },
  { time: 0.33, title: "180BPMの1拍", description: "180BPM＝1拍0.33秒。速いダンス。", category: "音楽" },
  { time: 332, title: "Thriller", description: "マイケル・ジャクソン約5分32秒（332秒）。", category: "音楽" },
  { time: 276, title: "Don't Stop Believin'", description: "ジャーニー約4分36秒（276秒）。", category: "音楽" },
  { time: 318, title: "Wonderwall", description: "オアシス約4分38秒（318秒）。", category: "音楽" },
  { time: 266, title: "Creep", description: "レディオヘッド約3分56秒（266秒）。", category: "音楽" },
  { time: 223, title: "Smells Like Teen Spirit（短）", description: "Nirvana約3分43秒。223秒版。", category: "音楽" },
];
