const EVENTS_FOOD = [
  { time: 3.0, title: "インスタントラーメン1分", description: "1分で食べられるラーメンもあったが1984年に終了。", category: "食" },
  { time: 180.0, title: "カップヌードル3分", description: "安藤百福が決めた3分。麺が戻りスープが溶ける時間。", category: "食" },
  { time: 198.0, title: "カップ麺3.3分（ポット）", description: "ポットの90℃お湯なら3.3分が最適。", category: "食" },
  { time: 210.0, title: "カップ麺3分30秒", description: "お湯を入れて3分30秒。麺の吸水が進む。", category: "食" },
  { time: 240.0, title: "カップ麺4分", description: "袋麺をお湯だけで戻すなら4分。", category: "食" },
  { time: 300.0, title: "カップ麺5分", description: "袋麺お湯のみなら5分が茹で麺に近い。", category: "食" },
  { time: 330.0, title: "カップ麺5分30秒", description: "5分30秒までが理想的な食べ時間。", category: "食" },
  { time: 45.0, title: "半熟卵", description: "沸騰から45秒-1分。黄身とろ、白身固め。", category: "食" },
  { time: 60.0, title: "半熟卵1分", description: "1分茹で。黄身がとろり。", category: "食" },
  { time: 180.0, title: "ボイルドエッグ3分", description: "3分茹で。黄身とろ、白身固め。", category: "食" },
  { time: 420.0, title: "ゆで卵7分", description: "7分茹で。完全に固ゆで。", category: "食" },
  { time: 600.0, title: "ゆで卵10分", description: "10分茹で。黄身に緑の輪。", category: "食" },
  { time: 90.0, title: "パスタ al dente", description: "アルデンテは通常7-11分。90秒は硬い。", category: "食" },
  { time: 480.0, title: "パスタ8分", description: "乾麺パスタ8分が標準。", category: "食" },
  { time: 600.0, title: "パスタ10分", description: "10分茹で。やや柔らかめ。", category: "食" },
  { time: 30.0, title: "電子レンジ30秒", description: "温めの定番30秒。", category: "食" },
  { time: 60.0, title: "電子レンジ1分", description: "1分温め。スープやご飯。", category: "食" },
  { time: 120.0, title: "電子レンジ2分", description: "2分温め。冷凍食品。", category: "食" },
  { time: 15.0, title: "エスプレッソ抽出", description: "エスプレッソは25-30秒抽出。15秒は短い。", category: "食" },
  { time: 25.0, title: "エスプレッソ25秒", description: "理想的なエスプレッソ抽出25-30秒。", category: "食" },
  { time: 30.0, title: "エスプレッソ30秒", description: "30秒抽出。クリーマが現れる。", category: "食" },
  { time: 240.0, title: "紅茶4分", description: "英国式紅茶は3-5分蒸らし。", category: "食" },
  { time: 180.0, title: "日本茶3分", description: "煎茶は2-3分蒸らし。", category: "食" },
  { time: 60.0, title: "お茶1分", description: "急須で1分。濃い茶。", category: "食" },
  { time: 900.0, title: "コーヒー15分", description: "サイフォンやフレンチプレス15分。", category: "食" },
  { time: 300.0, title: "ステーキ5分", description: "1cm厚のステーキ片面5分。ミディアム。", category: "食" },
  { time: 180.0, title: "ステーキ3分", description: "レアなら片面3分。", category: "食" },
  { time: 720.0, title: "ローストビーフ", description: "低温調理60-90分。720秒は短い。", category: "食" },
  { time: 3600.0, title: "煮込み1時間", description: "カレーやシチュー1時間。", category: "食" },
  { time: 7200.0, title: "煮込み2時間", description: "骨付き肉の煮込み2時間。", category: "食" },
  { time: 3.0, title: "3秒ルール", description: "落とした食べ物3秒ルール（都市伝説）。", category: "食" },
  { time: 5.0, title: "5秒ルール", description: "5秒ルール版。細菌は即座に付着。", category: "食" },
  { time: 10.0, title: "うどん10秒", description: "茹で上がったうどんを10秒冷水。", category: "食" },
  { time: 120.0, title: "餃子2分", description: "フライパンで2-3分。", category: "食" },
  { time: 90.0, title: "トースト1.5分", description: "トースター1.5分。", category: "食" },
  { time: 1.3, title: "ビール1リットル世界記録", description: "1977年Steven Petrosinoが1.3秒で1Lビール。", category: "食" },
];
