const EVENTS_SCIENCE = [
  { time: 0.000001, title: "光が1km進む時間", description: "真空中で光は1秒間に約30万km進む。1kmなら約3.3マイクロ秒。", category: "科学" },
  { time: 0.000003, title: "光が1メートル進む", description: "光は約3ナノ秒で1m移動。物理学の基本定数。", category: "科学" },
  { time: 0.000015, title: "原爆の核分裂完了", description: "広島への原爆投下。ウラン235の核分裂が完了するまで約15マイクロ秒。", category: "科学" },
  { time: 0.000000001, title: "1ナノ秒", description: "現代のトランジスタはナノ秒単位でスイッチング。1秒は10億ナノ秒。", category: "科学" },
  { time: 0.002, title: "ニューロンのスパイク", description: "脳のニューロンが送る電気信号「スパイク」は約2ミリ秒続く。", category: "科学" },
  { time: 0.013, title: "脳が画像を認識", description: "人間の脳は目が見た画像をわずか13ミリ秒で処理できる。", category: "科学" },
  { time: 0.02, title: "世界最速のガン抜き", description: "ボブ・マンデンがリボルバーを抜いて撃つまで0.02秒。瞬きより速い。", category: "科学" },
  { time: 0.05, title: "雷の先端からの放電", description: "落雷の先端部分の放電過程は数十ミリ秒。目で追えない速度。", category: "科学" },
  { time: 0.103, title: "ロボットのルービックキューブ", description: "2025年、米国の学生チームが0.103秒で3×3キューブを完成。瞬きより速い。", category: "科学" },
  { time: 0.13, title: "光が地球1周", description: "光は約0.13秒で地球赤道1周（約4万km）を回れる。", category: "科学" },
  { time: 0.2, title: "原爆の火球が最大輝度", description: "原爆投下0.2秒後、火球直径310m・表面温度6000度で最も明るく見える。", category: "科学" },
  { time: 0.305, title: "三菱電機のキューブロボ", description: "2024年、三菱電機が0.305秒でルービックキューブを完成させた。", category: "科学" },
  { time: 0.38, title: "MITのキューブロボ", description: "2018年、MITのBen KatzとJared Di Carloが0.38秒の記録を樹立。", category: "科学" },
  { time: 0.51, title: "原爆の火球が縮み始める", description: "投下0.51秒後、火球が縮小し始め煙が出る。キノコ雲の前兆。", category: "科学" },
  { time: 0.637, title: "アルバート・ビーアのロボ", description: "2016年、ドイツのAlbert Beerが0.637秒でキューブを完成。", category: "科学" },
  { time: 1.0, title: "「1秒」の原子時計定義", description: "セシウム133原子の振動9,192,631,770回が1秒。1967年に定義が変更された。", category: "科学" },
  { time: 1.3, title: "光が月まで到達", description: "地球から月（約38.4万km）まで光は約1.3秒。", category: "科学" },
  { time: 1.7, title: "原爆のキノコ雲形成開始", description: "投下1.7秒後、キノコ雲の形成が始まる。衝撃波も地上を襲う。", category: "科学" },
  { time: 2.0, title: "原爆の火球直径310m", description: "0.2秒時点のデータだが、火球拡大の過程全体が2秒以内に熱線の90%を放出。", category: "科学" },
  { time: 3.0, title: "原爆の熱線が消える", description: "投下約3秒で熱線の影響は消える。衝撃波はまだ伝播中。", category: "科学" },
  { time: 3.33, title: "音の速度で1km", description: "音速（約340m/s）なら1kmを約2.94秒。3.33秒なら約1.13km。", category: "科学" },
  { time: 7.0, title: "ニコチンが脳に到達", description: "タバコを吸うとニコチンは約7秒で脳に到達する。", category: "科学" },
  { time: 7.2, title: "原爆の衝撃波3km到達", description: "投下7.2秒後、衝撃波は爆心地から約3km先に到達したと推定。", category: "科学" },
  { time: 10.1, title: "原爆の衝撃波4km到達", description: "投下10.1秒後、衝撃波は4km先まで到達。窓ガラスが砕け散った。", category: "科学" },
  { time: 12.0, title: "雷の光と音の差", description: "稲妻を見てから12秒後に雷が聞こえたら、約4km離れている。", category: "科学" },
  { time: 29.9792458, title: "光速（定義値）", description: "真空中の光速は秒速299,792,458m。物理学の基本定数。", category: "科学" },
  { time: 42.0, title: "生命、宇宙、そしてすべての答え", description: "ダグラス・アダムス『銀河ヒッチハイク・ガイド』。深い問いの答えは42。", category: "科学" },
  { time: 60.0, title: "アルコールが脳に到達", description: "飲酒後、アルコールが脳に影響を与えるまで約6分（360秒）。", category: "科学" },
  { time: 90.0, title: "血液が体1周", description: "人間の血液は約60〜90秒で心臓から全身を1周する。", category: "科学" },
  { time: 120.0, title: "MRI1枚の撮影", description: "磁気共鳴画像（MRI）の1スライス撮影に数秒〜数十秒。", category: "科学" },
  { time: 180.0, title: "DNA複製の1回", description: "細胞分裂時、DNAの複製開始から完了まで数分。核心部分は数秒単位。", category: "科学" },
  { time: 360.0, title: "アルコールが脳に到達（6分）", description: "アルコールが血液から脳に到達するまで約6分。", category: "科学" },
  { time: 9192631770, title: "1秒の原子振動数", description: "セシウム133の振動回数。原子時計が刻む1秒の正体。", category: "科学" },
];
