const EVENTS_TECH = [
  { time: 0.000001, title: "CPU 1GHz 1サイクル", description: "1GHz＝1サイクル1ナノ秒。現代CPUは数GHz。", category: "テクノロジー" },
  { time: 0.000000001, title: "1ナノ秒", description: "トランジスタのスイッチングはナノ秒単位。", category: "テクノロジー" },
  { time: 0.000001, title: "1マイクロ秒", description: "メモリアクセスはマイクロ秒〜ナノ秒。", category: "テクノロジー" },
  { time: 0.001, title: "1ミリ秒", description: "人間が知覚できる最短の遅延。ゲーム60fps＝16.7ms。", category: "テクノロジー" },
  { time: 0.0167, title: "60fpsの1フレーム", description: "60fps＝1フレーム16.7ミリ秒。", category: "テクノロジー" },
  { time: 0.033, title: "30fpsの1フレーム", description: "30fps＝1フレーム33ミリ秒。", category: "テクノロジー" },
  { time: 0.008, title: "120fpsの1フレーム", description: "120fps＝1フレーム8.3ミリ秒。VR向け。", category: "テクノロジー" },
  { time: 0.1, title: "人間が知覚する遅延", description: "100ms以上の遅延を人間は体感する。", category: "テクノロジー" },
  { time: 0.2, title: "ゲームの入力遅延目標", description: "プロゲーマーは20ms以下を求める。", category: "テクノロジー" },
  { time: 1.0, title: "Ping 1秒", description: "1秒のPingはゲームでは致命的。", category: "テクノロジー" },
  { time: 0.05, title: "光ファイバー国内遅延", description: "国内通信の往復遅延は数ms〜数十ms。", category: "テクノロジー" },
  { time: 0.15, title: "東京-大阪 光遅延", description: "約500km。往復約5ms。150msは余裕。", category: "テクノロジー" },
  { time: 0.2, title: "東京-シドニー 光遅延", description: "約7800km。往復約130ms。", category: "テクノロジー" },
  { time: 0.13, title: "光が地球1周", description: "光は0.13秒で地球1周。インターネットの物理限界。", category: "テクノロジー" },
  { time: 0.103, title: "ロボットルービックキューブ", description: "2025年0.103秒。人間の限界を超えた。", category: "テクノロジー" },
  { time: 29.12, title: "人間のルービックキューブ", description: "2023年マックス・パーク29.12秒。", category: "テクノロジー" },
  { time: 3.47, title: "GPT-4の応答開始", description: "大規模言語モデルの初回トークン生成は数秒。", category: "テクノロジー" },
  { time: 0.5, title: "音声認識の遅延", description: "リアルタイム音声認識は500ms以内が目標。", category: "テクノロジー" },
  { time: 2.0, title: "Google検索", description: "検索結果表示は通常0.5-2秒。", category: "テクノロジー" },
  { time: 5.0, title: "Windows起動（SSD）", description: "SSDなら10-30秒。5秒は理想。", category: "テクノロジー" },
  { time: 30.0, title: "Windows起動（HDD）", description: "HDDなら1-2分。30秒はSSD。", category: "テクノロジー" },
  { time: 60.0, title: "スマホ充電1%", description: "急速充電でも1%あたり数秒〜。", category: "テクノロジー" },
  { time: 180.0, title: "スマホ0-100%充電", description: "急速充電で18-30分。180秒は約30%。", category: "テクノロジー" },
  { time: 3600.0, title: "1時間の動画ダウンロード", description: "回線速度による。3600秒＝1時間。", category: "テクノロジー" },
  { time: 0.02, title: "Bob Mundenのガン抜き", description: "0.02秒。人間の限界。", category: "テクノロジー" },
  { time: 0.305, title: "三菱キューブロボ2024", description: "0.305秒。産業用ロボの精度。", category: "テクノロジー" },
  { time: 0.38, title: "MITキューブロボ2018", description: "0.38秒。学生プロジェクトの頂点。", category: "テクノロジー" },
  { time: 64.0, title: "1964年のコンピュータ", description: "1964年、1分4秒でキューブ（ロボの始まり）。", category: "テクノロジー" },
  { time: 5.27, title: "2011年キューブロボ", description: "5.27秒。10年で100倍速に。", category: "テクノロジー" },
  { time: 0.887, title: "2016年Albert Beer", description: "0.887秒。1秒切りの記録。", category: "テクノロジー" },
  { time: 0.637, title: "2016年Albert Beer更新", description: "0.637秒。さらに速く。", category: "テクノロジー" },
  { time: 0.9, title: "2016年Jay Flatland", description: "0.9秒。1秒切り。", category: "テクノロジー" },
  { time: 2.39, title: "2015年Zackary Gromko", description: "2.39秒。ロボット競争の始まり。", category: "テクノロジー" },
  { time: 3.25, title: "2014年Mike Dobson", description: "3.253秒。英国チーム。", category: "テクノロジー" },
  { time: 5.27, title: "2011年キューブロボ", description: "5.27秒。ロボット時代の幕開け。", category: "テクノロジー" },
];
