const EVENTS_SPACE = [
  { time: 0.13, title: "光が地球1周", description: "光は約0.13秒で地球赤道1周（約40,075km）を進む。", category: "宇宙" },
  { time: 1.28, title: "光が月まで", description: "地球から月まで約384,399km。光は約1.28秒。", category: "宇宙" },
  { time: 8.3, title: "太陽光が地球に届く", description: "太陽から地球まで約1.5億km。光は約8分19秒（499秒）。", category: "宇宙" },
  { time: 499, title: "太陽光の旅（8分19秒）", description: "太陽表面で放たれた光が地球に届くまで499秒。今見える太陽は8分前の姿。", category: "宇宙" },
  { time: 500, title: "太陽光が地球到達", description: "499秒＝8分19秒。太陽の「今」は地球からは見えない。", category: "宇宙" },
  { time: 760, title: "太陽光が火星に到達", description: "太陽から火星まで光は約12分40秒（760秒）。", category: "宇宙" },
  { time: 2596, title: "太陽光が木星に到達", description: "太陽から木星まで光は約43分16秒。", category: "宇宙" },
  { time: 4768, title: "太陽光が土星に到達", description: "太陽から土星まで光は約1時間19分28秒。", category: "宇宙" },
  { time: 9146, title: "太陽光が天王星に到達", description: "太陽から天王星まで光は約2時間32分。", category: "宇宙" },
  { time: 15025, title: "太陽光が海王星に到達", description: "太陽から海王星まで光は約4時間10分。", category: "宇宙" },
  { time: 1.007, title: "国際宇宙ステーション1周", description: "ISSは約90分で地球1周。1周の約1/90が約1分＝60秒。", category: "宇宙" },
  { time: 5400, title: "ISSが地球1周", description: "国際宇宙ステーションは約90分（5400秒）で地球1周。", category: "宇宙" },
  { time: 108, title: "スペースシャトル上昇（初期）", description: "スペースシャトルは打ち上げ後約8分30秒（510秒）で軌道投入。", category: "宇宙" },
  { time: 510, title: "スペースシャトル軌道投入", description: "打ち上げから約8分30秒で低地球軌道に到達。", category: "宇宙" },
  { time: 238, title: "アポロ11月面着陸の最終降下", description: "月面着陸の最終降下フェーズ「パワー・デセント」は約12分。", category: "宇宙" },
  { time: 720, title: "アポロ11月面着陸", description: "月面着陸の最終降下から着陸まで約12分（720秒）の緊迫。", category: "宇宙" },
  { time: 3.0, title: "月面着陸の最終3秒", description: "「ホーストン、トランクイリティ・ベースこちらイーグル。オーバー。」", category: "宇宙" },
  { time: 11.0, title: "アポロ13の名言", description: "「ヒューストン、問題が発生した。」（Houston, we have a problem）", category: "宇宙" },
  { time: 0.001, title: "隕石の大気圏突入", description: "隕石が大気圏に突入して輝く時間は通常1秒未満。", category: "宇宙" },
  { time: 31536000, title: "1光年（秒換算）", description: "1年＝31,536,000秒。光年は約9.46兆km。", category: "宇宙" },
  { time: 86400, title: "1光日", description: "光が1日で進む距離は約259億km。太陽系の外縁へ。", category: "宇宙" },
  { time: 3600, title: "1光時", description: "光が1時間で進む距離は約10.8億km。木星と土星の間。", category: "宇宙" },
  { time: 60, title: "1光分", description: "光が1分で進む距離は約1800万km。水星軌道の3分の1。", category: "宇宙" },
  { time: 1.0, title: "1光秒", description: "光が1秒で進む距離は約30万km。地球と月の距離より短い。", category: "宇宙" },
  { time: 13.8, title: "宇宙の年齢（×10億年）", description: "138億年。秒に換算すると435兆秒以上。", category: "宇宙" },
];
