const EVENTS_CULTURE = [
  { time: 15, title: "テレビCM15秒", description: "日本のCM標準尺。15秒で商品を売る。", category: "文化" },
  { time: 30, title: "テレビCM30秒", description: "CMの定番30秒。情報と感情を詰め込む。", category: "文化" },
  { time: 60, title: "1分CM", description: "長尺CM。ストーリーを語る時間。", category: "文化" },
  { time: 42, title: "生命、宇宙、そしてすべての答え", description: "『銀河ヒッチハイク・ガイド』。42は究極の答え。", category: "文化" },
  { time: 88, title: "Back to the Future", description: "1985年。88mph（時速約142km）でタイムトラベル。", category: "文化" },
  { time: 142, title: "Back to the Future 88mph", description: "88mph＝約39m/s。142km/h換算。", category: "文化" },
  { time: 120, title: "映画の平均シーン長", description: "現代映画のシーンは平均2-3分。120秒は1シーン。", category: "文化" },
  { time: 180, title: "3分のショートフィルム", description: "短編映画の定番尺3分。", category: "文化" },
  { time: 600, title: "10分のWebドラマ", description: "YouTube等の短編ドラマ10分。", category: "文化" },
  { time: 7200, title: "2時間の映画", description: "長編映画の標準2時間＝7200秒。", category: "文化" },
  { time: 5400, title: "90分の映画", description: "短めの長編映画90分。", category: "文化" },
  { time: 0.04, title: "映画24fpsの1コマ", description: "24fpsなら1コマ約0.042秒。映画の1フレーム。", category: "文化" },
  { time: 0.033, title: "30fpsの1コマ", description: "30fpsなら1コマ約0.033秒。テレビの1フレーム。", category: "文化" },
  { time: 0.017, title: "60fpsの1コマ", description: "60fpsなら1コマ約0.017秒。ゲームの滑らかさ。", category: "文化" },
  { time: 2.0, title: "映画の2秒ルール", description: "ショットは2秒以上続けると認識されやすい。", category: "文化" },
  { time: 5.0, title: "YouTubeの5秒スキップ", description: "5秒後にスキップ可能な広告。", category: "文化" },
  { time: 6.0, title: "TikTokの6秒", description: "TikTokの最短動画6秒。", category: "文化" },
  { time: 15.0, title: "Instagram Reels15秒", description: "Reelsの短尺15秒。", category: "文化" },
  { time: 60.0, title: "TikTok最大1分", description: "TikTokの1分動画。", category: "文化" },
  { time: 180.0, title: "YouTube Shorts3分", description: "Shortsの最大3分。", category: "文化" },
  { time: 86400.0, title: "1日86400秒", description: "24時間＝86,400秒。1日の秒数。", category: "文化" },
  { time: 604800.0, title: "1週間", description: "7日＝604,800秒。", category: "文化" },
  { time: 2592000.0, title: "30日", description: "1ヶ月（30日）＝2,592,000秒。", category: "文化" },
  { time: 31536000.0, title: "1年", description: "365日＝31,536,000秒。", category: "文化" },
  { time: 3.0, title: "「3秒ルール」", description: "落とした食べ物は3秒以内なら拾える？（都市伝説）", category: "文化" },
  { time: 7.0, title: "7秒で第一印象", description: "心理学：第一印象は7秒で決まると言われる。", category: "文化" },
  { time: 10.0, title: "エレベーターピッチ", description: "10秒でアイデアを伝える時間。", category: "文化" },
  { time: 20.0, title: "Twitterの140字", description: "140字を20秒で読む。読了時間。", category: "文化" },
  { time: 45.0, title: "レコード1面", description: "LP1面は約20-25分。45秒は1曲。", category: "文化" },
  { time: 74.0, title: "30秒で74回のキス", description: "2017年ギネス。30秒で74回キスを受けた記録。", category: "文化" },
  { time: 28.0, title: "30秒で28足の靴下", description: "2018年、30秒で28足の靴下を履いた記録。", category: "文化" },
  { time: 0.5, title: "漫才のボケとツッコミ", description: "ツッコミの間は0.5秒以内が理想。", category: "文化" },
  { time: 1.5, title: "落語の拍子", description: "落語の「拍子」は1-2秒の間。", category: "文化" },
  { time: 4.0, title: "能の1拍", description: "能楽の拍子はゆったり。4秒1拍。", category: "文化" },
  { time: 108.0, title: "俳句の詠む時間", description: "俳句を詠むのに108秒。2分弱。", category: "文化" },
  { time: 17.0, title: "ハイクの17音", description: "俳句17音を詠む時間。", category: "文化" },
  { time: 31.0, title: "短歌31音", description: "短歌31音を詠む時間。", category: "文化" },
];
